sudo: false
language: python
python:
- '2.7'
cache:
  directories:
  - "$HOME/gcloud/"
env:
  global:
  - PATH=$PATH:$HOME/gcloud/google-cloud-sdk/bin GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/client-secret.json
before_install:
- openssl aes-256-cbc -K $encrypted_42099b4af021_key -iv $encrypted_42099b4af021_iv -in client-secret.json.enc -out client-secret.json -d
- if [ ! -d $HOME/gcloud/google-cloud-sdk ]; then mkdir -p $HOME/gcloud && wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
  --directory-prefix=$HOME/gcloud && cd $HOME/gcloud && tar xzf google-cloud-sdk.tar.gz
  && printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh && cd $TRAVIS_BUILD_DIR;
  fi
- gcloud -q components update
- gcloud -q auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
- gcloud config set project timetrackerbteam
install:
- echo "Instalando"
before_script:
- echo "Before script"
script:
- echo "Script"
after_success:
- gcloud -q app deploy /TimeTrackerBTeam/Server/app.yaml
