runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /_ah/spi/.*
  script: main.app

- url: /(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2))
  static_files: public/\1
  upload: public/(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2))

- url: /.*
  static_files: public/index.html
  upload: public/index.html
  secure: always

- url: /bootstrap
  static_dir: bootstrap

# [END handlers]

# [START libraries]
libraries:
- name: endpoints
  version: "1.0"
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
