runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /_ah/spi/.*
  script: main.app

- url: /bootstrap
  static_dir: bootstrap

# [END handlers]

# [START libraries]
libraries:
- name: endpoints
  version: "1.0"
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
